POST http://localhost:3000/register
Content-Type: application/json

{
    "userName":"Karthik1234",
    "email":"Karthik@123",
    "password":"Karthik1234564"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "userName":"Karthik1234",
    "password":"Karthik1234564"
}